src/analysis/urls.py
from django.urls import path, include
from django.views.generic import RedirectView

from analysis.views import check_auth, full_sync
from core.admin import admin_site
from core.services.integrations.telegram_bot import handle_request

urlpatterns = [
    path("", RedirectView.as_view(url="/admin")),
    path("crm/", include("crm.urls")),
    path("auth_check/", check_auth),
    path("auth/", include("social_django.urls", namespace="social")),
    path("admin/", admin_site.urls),
    path("", include("core.urls")),
    path("webhook/worker/", full_sync),
    path("webhook/bot", handle_request),
]

src/crm/urls.py
from django.urls import path

from crm.views import (
    projects_weekly_summary_api,
    project_weekly_summary_api,
    analysis_view,
    project_info,
    projects_last_update_api,
    project_tasks_tabel_view,
    project_sync_tasks,
    start_code_analysis,
)

app_name = "crm"

urlpatterns = [
    path("analysis/", analysis_view, name="analysis"),
    path("analysis/start_code_analysis/", start_code_analysis, name="start_code_analysis"),
    path("project_tasks_tabel/", project_tasks_tabel_view, name="project_tasks_tabel"),
    path("project_info_cell/<int:project_id>/", project_info),
    path("sync_project_tasks/<int:project_id>/", project_sync_tasks, name="project_sync_tasks"),
    path("api/projects_last_update_summary/", projects_last_update_api),
    path("api/projects_weekly_summary/", projects_weekly_summary_api),
    path("api/projects_weekly_summary/<int:project_id>/", project_weekly_summary_api),
]

src/crm/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import UniqueConstraint
from django.utils.formats import date_format

from core.models import Project, Member
from core.models.base import BaseModel
from core.models.project import ProjectTechnology

User = get_user_model()


class CrmProject(Project):
    class Meta:
        proxy = True
        verbose_name = "Проект"
        verbose_name_plural = "Проекты"


class CrmMember(Member):
    def __str__(self):
        name = self.full_name
        if self.is_staff:
            name += f" ({self.subdivision or 'сотрудник'})"
        elif self.group:
            name += f" ({self.group})"
        return name

    class Meta:
        proxy = True
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"


class CrmProjectTechnology(ProjectTechnology):
    class Meta:
        proxy = True
        verbose_name = "Технология"
        verbose_name_plural = "Технологии"


class ProjectMember(BaseModel):
    project = models.ForeignKey(CrmProject, on_delete=models.CASCADE, verbose_name="Проект")
    member = models.ForeignKey(CrmMember, on_delete=models.CASCADE, verbose_name="Контакт")
    comment = models.TextField(verbose_name="Комментарий", blank=True, null=True)
    is_old = models.BooleanField(default=False, verbose_name="Участвовал в прошлом")

    class Meta:
        verbose_name = "Участие в проекте"
        verbose_name_plural = "Участия в проектах"
        constraints = [UniqueConstraint(fields=("project", "member"), name="project_member_unique")]


class ProjectStakeholder(BaseModel):
    project = models.ForeignKey(CrmProject, on_delete=models.CASCADE, verbose_name="Проект")
    member = models.ForeignKey(CrmMember, on_delete=models.CASCADE, verbose_name="Контакт")
    comment = models.TextField(verbose_name="Комментарий", blank=True, null=True)

    class Meta:
        verbose_name = "Заинтересованное лицо"
        verbose_name_plural = "Заинтересованные лица"


class ProjectComment(BaseModel):
    project = models.ForeignKey(CrmProject, on_delete=models.CASCADE, verbose_name="Проект")
    # сначала сохраняются все модели в админке, которые есть во всех инлайнах, а вторым сохранением добавляются авторы.
    # Если это не сделать, тодга операции удаления не будут работать в других инлайнах, и это плохо
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    text = models.TextField()

    def __str__(self):
        return f'{self.author} в {date_format(self.created_at, "DATETIME_FORMAT")}'

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


class ProjectTask(BaseModel):
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(CrmProject, on_delete=models.CASCADE, verbose_name="Проект", related_name="tasks")
    title = models.CharField(max_length=500)
    date = models.DateField(null=True, blank=True, verbose_name="Крайний срок")
    mark = models.IntegerField(null=True, blank=True, verbose_name="Оценка")
    added_to_trello = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Ключевая задача"
        verbose_name_plural = "Задачи"


class LogsWithMembers(models.Model):
    """Модель получения данных для событий по неделям в аналитике."""

    project_id = models.IntegerField()
    member_full_name = models.CharField(max_length=255)
    provider = models.CharField(max_length=50)
    date = models.DateField()
    week_start_date = models.TextField()

    class Meta:
        managed = False
        db_table = "logs_with_members"

src/analysis/views.py
from concurrent.futures import ThreadPoolExecutor

from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt

from core.services.integrations.main import full_sync as full_sync_service

executor = ThreadPoolExecutor()


@csrf_exempt
def check_auth(request):
    if not request.user.is_superuser:
        return JsonResponse({"status": "error"}, status=401)
    return JsonResponse(
        {"status": "ok", "id": request.user.id, "email": request.user.username},
        headers={"X-WEBAUTH-ID": request.user.id, "X-WEBAUTH-USER": request.user.username},
    )


@csrf_exempt
def full_sync(request):
    task = executor.submit(full_sync_service)
    return HttpResponse(b"ok", status=200)

src/crm/views.py
from datetime import datetime

from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from rest_framework.decorators import api_view
from rest_framework.response import Response

from crm.models import CrmProject
from crm.services.analysis.code import start_code_analysis_for_all_repos
from crm.services.analysis.project_summary import ProjectSummaryService
from crm.services.analysis.projects_last_update_summary import ProjectsLastUpdateSummaryService
from crm.services.analysis.projects_weekly_summary import ProjectsWeeklySummaryService
from crm.services.project_tasks_tabel import get_info
from crm.services.sync_tasks_to_trello import sync_project_tasks
from crm.utils import get_project_name_cell


def start_end_dates_params(func):
    def wrap(request, *args, **kwargs):
        params = request.GET
        start_date = datetime.strptime(params.get("start", None), "%Y-%m-%d") if "start" in params else None
        end_date = datetime.strptime(params.get("end", None), "%Y-%m-%d") if "end" in params else None

        return func(request, *args, start_date=start_date, end_date=end_date, **kwargs)

    return wrap


@staff_member_required
@api_view(["GET"])
@start_end_dates_params
def projects_weekly_summary_api(request, **kwargs):
    project_id = request.GET.get("project_id", None)
    return Response(ProjectsWeeklySummaryService(project_id=project_id, **kwargs).run())


@staff_member_required
@api_view(["GET"])
@start_end_dates_params
def project_weekly_summary_api(request, project_id, **kwargs):
    user_id = request.GET.get("user_id", None)
    return Response(ProjectSummaryService(project_id, user_id=user_id, **kwargs).run())


@staff_member_required
@api_view(["GET"])
def projects_last_update_api(request):
    return Response(ProjectsLastUpdateSummaryService().run())


@staff_member_required
def project_info(request, project_id):
    project = get_object_or_404(CrmProject, id=project_id)
    return HttpResponse(get_project_name_cell(project))


@staff_member_required
def analysis_view(request):
    return render(request, "crm_admin/analysis.html")


@staff_member_required
def project_tasks_tabel_view(request):
    return render(request, "crm_admin/project_tasks_tabel.html", get_info())


@staff_member_required
def project_sync_tasks(request, project_id):
    project = get_object_or_404(CrmProject, id=project_id)
    sync_project_tasks(project.id)
    return redirect(request.META["HTTP_REFERER"])


@staff_member_required
def start_code_analysis(request):
    start_code_analysis_for_all_repos()
    return redirect(request.META["HTTP_REFERER"])

src/crm/templates/crm_admin/analysis.html
{% extends "admin/base.html" %}
{% load static %}
{% block page_content %}
    <div id="app" class="col-md-12">
        <h3 class="text-center">Загрузка...</h3>
    </div>
{% endblock %}


{% block extrajs %}
    {{ block.super }}
    <script type="module" src="{% static 'crmwebapp/dist/vendor.js' %}"></script>
    <script type="module" src="{% static 'crmwebapp/dist/analysis.js' %}"></script>
    <link rel="stylesheet" href="{% static 'crmwebapp/dist/assets/analysis.css' %}">
{% endblock %}

src/crm/templates/crm_admin/project_tasks_change_list.html
{% extends "admin/change_list.html" %}
{% load i18n admin_list static %}
{% load crmadmin %}
{% block content_title %}{% endblock %}
{% block breadcrumbs %}
{% endblock %}
{% block content %}
    <div class="col-md-2">
        <div class="input-group mb-1">
            <input type="text" class="form-control" placeholder="Поиск" id="searchinput" name="q" autocomplete="off">
        </div>
        <div class="list-group" id="projects_sidebar">
            {% for project in projects %}
                <a
                    href="?project__id__exact={{ project.id }}"
                    class="list-group-item list-group-item-action importance-{{ project.importance }}"
                    id="projectLink{{ project.id }}"
                >
                    {% include 'crm_admin/partials/project.html' %}
                </a>
            {% endfor %}
        </div>
    </div>
    <div class="col-10">
        <div class="card card-primary card-outline">
            <div class="card-header projects-card-header">
                <h4 class="card-title">{{ cl.opts.verbose_name_plural|capfirst }}{% block pretitle %}{% endblock %}</h4>
                <div class="card-tools form-inline">
                    <a class="btn btn-outline-secondary btn-sm mr-1 mt-2" href="{% url 'crm:project_tasks_tabel' %}">Табель</a>
                    {% block date_hierarchy %}{% if cl.date_hierarchy %}{% date_hierarchy cl %}{% endif %}{% endblock %}
                    {% block search %}
                        {% search_form cl %}
                    {% endblock %}
                </div>
            </div>

            <div class="card-body">
                <div id="content-main">
                    {% if cl.formset and cl.formset.errors %}
                    <p class="errornote">
                        {% if cl.formset.total_error_count == 1 %}
                            {% trans "Please correct the error below." %}
                        {% else %}
                            {% trans "Please correct the errors below." %}
                        {% endif %}
                    </p>
                    {{ cl.formset.non_form_errors }}
                    {% endif %}
                    <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
                    <div class="row">
                        <div class="col-12">
                            {% if cl.formset %}
{#                                    <div>{{ cl.formset.management_form }}</div>#}
                            {% endif %}

                            {% block result_list %}
                                {% tasks_result_list cl %}
                                {% if action_form and actions_on_bottom and cl.show_admin_actions %}
                                    <form id="changelist-form" method="post"{% if cl.formset and cl.formset.is_multipart %}enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}
                                        <div class="row">
                                            <div class="col-12">
                                                {% admin_actions %}
                                            </div>
                                        </div>
                                    </form>
                                {% endif %}
                            {% endblock %}
                        </div>
                    </div>
                    <div class="row">
                        {% block pagination %}{% pagination cl %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>

    </div>
        <br class="clear"/>
    </div>
{% endblock %}


{% block extrajs %}
    {{ block.super }}
    <script src="{% static 'crm_admin/js/projects_sidebar_search.js' %}"></script>
    <script src="{% static 'crm_admin/js/project_tasks.js' %}"></script>
    <script type="module" src="{% static 'crmwebapp/dist/vendor.js' %}"></script>
    <script type="module" src="{% static 'crmwebapp/dist/projectTasks.js' %}"></script>
{% endblock %}

src/crm/templates/crm_admin/project_tasks_change_list_results.html
{% load i18n static jazzmin crmadmin %}

{% if result_hidden_fields %}
    <div class="hiddenfields">
        {% for item in result_hidden_fields %}{{ item }}{% endfor %}
    </div>
{% endif %}

{% if project %}
    <div class="row">
        <div class="col">
            {{ project_name }}
            <br>
            <button class="btn btn-outline-secondary btn-sm mr-1 mt-2" id="startButton">Аналитика</button>
            <a href="{% url 'crm:project_sync_tasks' project.id %}" class="btn btn-outline-secondary btn-sm mr-1 mt-2" title="Отправить задачи в Trello">Задачи -> Trello</a>
        </div>
        <div class="col">
            <b>Ссылки</b><br>
            {{ project.links|html_links }}<br>
            {{ project_services }}
        </div>
        <div class="col">
            <b>Заинтересованные лица</b><br>
            {{ project_stakeholders }}
        </div>
        <div class="col">
            <b>Команда</b><br>
            {{ project_members }}
        </div>
    </div>
    <script>
        window.projectId = "{{ project.id }}";
    </script>
    <div id="analyticsApp"></div>
    <hr>
{% endif %}

<form class="input-group mb-3" id="task-new" action="{% url 'admin:crm_projecttask_add' %}" method="post" novalidate="" style="display: none">
    {% csrf_token %}
    <label class="input-group-text">
        <input type="checkbox" name="is_completed">
    </label>
    <input type="hidden" name="project">
    <input name="title" class="form-control" placeholder="Новая задача">
    <input type="date" class="form-control" name="date" value="{{ task.date|date:'Y-m-d'|default_if_none:'' }}" style="flex: 0 0 130px">
    <input type="number" min="1" max="5" class="form-control" name="mark" value="" style="flex: 0 0 130px" placeholder="Оценка">
    <button class="btn btn-primary" title="Сохранить"><i class="fa fa-save"></i></button>
</form>

{% if results %}
    {% update_variable 0 as prev_project_id %}
    {% for task in queryset %}
        {% if prev_project_id != task.project_id and not project %}
            <hr>
            <p>
                <a href="?project__id__exact={{ task.project.id }}">
                    <b class="importance-{{ task.project.importance }}">
                        {% include 'crm_admin/partials/project.html' with project=task.project %}
                    </b>
                </a>
            </p>
        {% endif %}
        <form class="input-group mb-3 task-row" action="{% url 'admin:crm_projecttask_change' task.id %}" method="post" novalidate="">
            {% csrf_token %}
            <label class="input-group-text">
                <input type="checkbox" name="is_completed" {% if task.is_completed %}checked{% endif %}>
            </label>
            <input type="hidden" name="project" value="{{ task.project_id }}">
            <span class="form-control task-content">{{ task.title|html_links }}</span>
            <textarea name="title" class="form-control" style="display: none">{{ task.title }}</textarea>
            <input type="date" class="form-control" name="date" value="{{ task.date|date:'Y-m-d'|default_if_none:'' }}" style="flex: 0 0 130px">
            <input type="number" min="1" max="5" class="form-control" name="mark" value="{{ task.mark|default_if_none:'' }}" style="flex: 0 0 130px" placeholder="Оценка">
            <a class="btn btn-danger btn-sm" href="{% url 'admin:crm_projecttask_delete' task.id %}?_changelist_filters=project__id__exact%3D{{ task.project_id }}" title="Удалить">
                <i class="fa fa-trash"></i>
            </a>
        </form>
        {% update_variable task.project_id as prev_project_id %}
    {% endfor %}
{% endif %}

src/crm/templates/crm_admin/project_tasks_tabel.html
{% extends "admin/base.html" %}
{% load crmadmin %}
{% load static %}
{% block page_content %}
    <div class="container-fluid">
        <h1>Табель</h1>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered table-hover table-striped table-responsive">
                    <thead>
                        <tr>
                            <th>Проект</th>
                            <th>Сумма средних</th>
                            <th>Среднее средних</th>
                            {% for date in week_start_dates %}
                                <th>{{ date | date }}</th>
                            {% endfor %}
                        </tr>
                    </thead>
                    <tbody>
                        {% for project in projects %}
                            <tr>
                                <th>{{ project.name }}</th>
                                <th>{{ project.grouped_tasks_sum }}</th>
                                <th>{{ project.grouped_tasks_sum_avg }}</th>
                                {% for date in week_start_dates %}
                                    <td>
                                        {{ project.grouped_tasks_avg|dict_get:date }}
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

src/crm/templates/crm_admin/projects_change_form.html
{% extends 'admin/change_form.html' %}
{% load static %}
{% block content_title %}{% endblock %}
{% block breadcrumbs %}{% endblock %}
{% block pretitle %}{% endblock %}
{% block content %}
    <div class="row" id="project_edit_form">
        <div class="col-md-2">
            <form class="input-group mb-1" action="{% url 'admin:crm_crmproject_changelist' %}">
                <a class="btn btn-outline-secondary" title="Назад" href="{% url 'admin:crm_crmproject_changelist' %}">
                    <i class="fa fa-arrow-left"></i>
                </a>
                <input type="text" class="form-control" placeholder="Поиск" id="searchinput" name="q" autocomplete="off">
            </form>
            <div class="list-group" id="projects_sidebar">
                {% for project in projects %}
                    <a href="{% url 'admin:crm_crmproject_change' project.id %}"
                       class="list-group-item list-group-item-action  importance-{{ project.importance }}">
                        {% include 'crm_admin/partials/project.html' %}
                    </a>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-10">
            {{ block.super }}
        </div>
    </div>

{% endblock %}

{% block extrajs %}
    {{ block.super }}
    <script src="{% static 'crm_admin/js/projects_sidebar_search.js' %}"></script>
{% endblock %}

src/crm/templates/crm_admin/projects_change_list.html
{% extends "admin/change_list.html" %}
{% load static %}
{% load i18n admin_list %}
{% load crmadmin %}
{% block content_title %}{% endblock %}
{% block breadcrumbs %}
{% endblock %}
{% block content %}
    <div class="col-12" >
        <div id="app"></div>
        <div id="djangoContent" class="card card-primary card-outline">
            <div class="card-header projects-card-header">
                <h4 class="card-title">{{ cl.opts.verbose_name_plural|capfirst }}{% block pretitle %}{% endblock %}</h4>
                <div class="card-tools form-inline">
                    <button class="btn btn-outline-secondary btn-sm mr-1 mt-2" id="startButton">Аналитика</button>
                    {% block date_hierarchy %}{% if cl.date_hierarchy %}{% date_hierarchy cl %}{% endif %}{% endblock %}
                    {% block search %}
                        {% search_form cl %}
                    {% endblock %}
                </div>
            </div>

            <div class="card-body">
                <form id="changelist-form" method="post"{% if cl.formset and cl.formset.is_multipart %}enctype="multipart/form-data"{% endif %} novalidate>{% csrf_token %}
                    <div id="content-main">
                        {% if cl.formset and cl.formset.errors %}
                        <p class="errornote">
                            {% if cl.formset.total_error_count == 1 %}
                                {% trans "Please correct the error below." %}
                            {% else %}
                                {% trans "Please correct the errors below." %}
                            {% endif %}
                        </p>
                        {{ cl.formset.non_form_errors }}
                        {% endif %}
                        <div class="module{% if cl.has_filters %} filtered{% endif %}" id="changelist">
                        <div class="row">
                            <div class="col-12">
                                {% if cl.formset %}
                                    <div>{{ cl.formset.management_form }}</div>
                                {% endif %}

                                {% block result_list %}
                                    <div class="row">
                                        <div class="col-12 col-sm-8">
                                            {% if action_form and actions_on_top and cl.show_admin_actions %}
                                                {% admin_actions %}
                                            {% endif %}
                                        </div>
                                        <div class="col-12 col-sm-4">
                                            {% block object-tools %}
                                                {% block object-tools-items %}
                                                    {% change_list_object_tools %}
                                                {% endblock %}
                                            {% endblock %}
                                        </div>
                                    </div>
                                    {% projects_result_list cl %}
                                    {% if action_form and actions_on_bottom and cl.show_admin_actions %}
                                        <div class="row">
                                            <div class="col-12">
                                                {% admin_actions %}
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endblock %}
                            </div>
                        </div>
                        <div class="row">
                            {% block pagination %}{% pagination cl %}{% endblock %}
                        </div>
                    </div>
                    </div>
                </form>
            </div>

        </div>
        <br class="clear"/>
    </div>

    <script type="module" src="{% static 'crmwebapp/dist/vendor.js' %}"></script>
    <script type="module" src="{% static 'crmwebapp/dist/projectsList.js' %}"></script>
{% endblock %}

src/crm/templates/crm_admin/projects_change_list_results.html
{% load i18n static jazzmin %}

{% if result_hidden_fields %}
<div class="hiddenfields">
    {% for item in result_hidden_fields %}{{ item }}{% endfor %}
</div>
{% endif %}

{% if results %}
    <div class="table-responsive p-0 projects-table">
        <table id="result_list" class="table table-striped">
            <thead>
                <tr>
                    {% for header in result_headers %}
                    <th class="{% header_class header forloop %}" tabindex="0" rowspan="1" colspan="1">
                        <div class="text">
                            {% if header.sortable %}
                                <a href="{{ header.url_primary }}">{{ header.text|capfirst }}</a>
                            {% else %}
                                <span>{{ header.text|capfirst }}</span>
                            {% endif %}
                            {% if header.sorted %}
                                <a href="{{ header.url_remove }}">
                                    <div style="margin-top: .2em;" class="fa fa-times float-right"> </div>
                                </a>
                                {% if header.ascending %}
                                    <i style="margin-top: .2em;" class="fa fa-sort-alpha-down"> </i>
                                {% else %}
                                    <i style="margin-top: .2em;" class="fa fa-sort-alpha-up"> </i>
                                {% endif %}
                            {% endif %}
                        </div>
                    </th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                {% for result in results %}
                    <tr role="row" class="{% cycle 'even' 'odd' %} importance-{{ result.importance }}">
                        {% for item in result %}{{ item }}{% endfor %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endif %}